2018-02-21 11:36:28,660 ERROR: Exception on /unvote/3 [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/broccoli/161220049_web_programming/blog/app/routes.py", line 180, in unvote
    if not post.vote_num>0:
AttributeError: 'Post' object has no attribute 'vote_num'
2018-02-21 11:36:30,043 ERROR: Exception on /unvote/3 [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/broccoli/161220049_web_programming/blog/app/routes.py", line 180, in unvote
    if not post.vote_num>0:
AttributeError: 'Post' object has no attribute 'vote_num'
2018-02-21 11:36:38,161 ERROR: Exception on /unvote/3 [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/broccoli/161220049_web_programming/blog/app/routes.py", line 180, in unvote
    if not post.vote_num>0:
AttributeError: 'Post' object has no attribute 'vote_num'
2018-02-21 11:36:45,430 ERROR: Exception on /unvote/2 [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/broccoli/161220049_web_programming/blog/app/routes.py", line 180, in unvote
    if not post.vote_num>0:
AttributeError: 'Post' object has no attribute 'vote_num'
2018-02-21 11:38:45,762 INFO: Blog startup [in /home/broccoli/161220049_web_programming/blog/app/__init__.py:44]
2018-02-21 11:45:04,437 INFO: Blog startup [in /home/broccoli/161220049_web_programming/blog/app/__init__.py:44]
2018-02-21 11:49:19,015 INFO: Blog startup [in /home/broccoli/161220049_web_programming/blog/app/__init__.py:44]
2018-02-21 11:57:43,457 INFO: Blog startup [in /home/broccoli/161220049_web_programming/blog/app/__init__.py:44]
2018-02-21 12:07:44,262 INFO: Blog startup [in /home/broccoli/161220049_web_programming/blog/app/__init__.py:44]
2018-02-21 12:07:57,747 ERROR: Exception on /vote/3 [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1725, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2018-02-21 12:10:47,668 INFO: Blog startup [in /home/broccoli/161220049_web_programming/blog/app/__init__.py:44]
2018-02-21 12:50:44,203 INFO: Blog startup [in /home/broccoli/161220049_web_programming/blog/app/__init__.py:44]
2018-02-21 13:14:04,881 INFO: Blog startup [in /home/broccoli/161220049_web_programming/blog/app/__init__.py:44]
2018-02-21 13:14:25,336 ERROR: Exception on /leave_message/hych [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/broccoli/161220049_web_programming/blog/app/routes.py", line 191, in leave_message
    form = MessageForm()
NameError: global name 'MessageForm' is not defined
2018-02-21 13:14:35,725 ERROR: Exception on /leave_message/hych [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/broccoli/161220049_web_programming/blog/app/routes.py", line 191, in leave_message
    form = MessageForm()
NameError: global name 'MessageForm' is not defined
2018-02-21 13:14:49,312 INFO: Blog startup [in /home/broccoli/161220049_web_programming/blog/app/__init__.py:44]
2018-02-21 13:14:53,659 INFO: Blog startup [in /home/broccoli/161220049_web_programming/blog/app/__init__.py:44]
2018-02-21 13:14:55,259 ERROR: Exception on /leave_message/hych [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/broccoli/161220049_web_programming/blog/app/routes.py", line 191, in leave_message
    form = MessageForm()
NameError: global name 'MessageForm' is not defined
2018-02-21 13:17:38,252 INFO: Blog startup [in /home/broccoli/161220049_web_programming/blog/app/__init__.py:44]
