2018-02-22 12:47:58,200 ERROR: Exception on /post/3 [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/broccoli/161220049_web_programming/blog/app/routes.py", line 105, in post
    comments = post._comments().paginate(page, app.config['COMMENTS_PER_PAGE'], False)
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 491, in paginate
    items = self.limit(per_page).offset((page - 1) * per_page).all()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2726, in all
    return list(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2878, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2901, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such column: post.timestamp [SQL: u'SELECT comments.id AS comments_id, comments.body AS comments_body, comments.body_html AS comments_body_html, comments.timestamp AS comments_timestamp, comments.disabled AS comments_disabled, comments.author_id AS comments_author_id, comments.post_id AS comments_post_id \nFROM comments \nWHERE comments.post_id = ? ORDER BY post.timestamp DESC\n LIMIT ? OFFSET ?'] [parameters: (3, 5, 0)] (Background on this error at: http://sqlalche.me/e/e3q8)
2018-02-22 12:49:22,611 INFO: Blog startup [in /home/broccoli/161220049_web_programming/blog/app/__init__.py:44]
2018-02-22 12:49:29,293 INFO: Blog startup [in /home/broccoli/161220049_web_programming/blog/app/__init__.py:44]
2018-02-22 12:54:57,537 INFO: Blog startup [in /home/broccoli/161220049_web_programming/blog/app/__init__.py:44]
2018-02-22 12:55:03,976 ERROR: Exception on /post/3 [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/broccoli/161220049_web_programming/blog/app/routes.py", line 108, in post
    return render_template('_post.html', posts=post, form=form, comments=comments, next_url=next_url, prev_url=prev_url)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.10-py2.7.egg/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.10-py2.7.egg/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/broccoli/161220049_web_programming/blog/app/templates/_post.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/broccoli/161220049_web_programming/blog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/usr/local/lib/python2.7/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/usr/local/lib/python2.7/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/usr/local/lib/python2.7/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/usr/local/lib/python2.7/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/broccoli/161220049_web_programming/blog/app/templates/base.html", line 49, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/broccoli/161220049_web_programming/blog/app/templates/_post.html", line 6, in block "app_content"
    {% include 'post.html' %}
  File "/home/broccoli/161220049_web_programming/blog/app/templates/post.html", line 4, in top-level template code
    <a href="{{ url_for('user', username=post.author.username) }}">
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.10-py2.7.egg/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'post' is undefined
2018-02-22 12:56:21,877 INFO: Blog startup [in /home/broccoli/161220049_web_programming/blog/app/__init__.py:44]
2018-02-22 12:56:24,683 ERROR: Exception on /post/3 [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/broccoli/161220049_web_programming/blog/app/routes.py", line 108, in post
    return render_template('_post.html', post=post, form=form, comments=comments, next_url=next_url, prev_url=prev_url)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.10-py2.7.egg/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.10-py2.7.egg/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/broccoli/161220049_web_programming/blog/app/templates/_post.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/broccoli/161220049_web_programming/blog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/usr/local/lib/python2.7/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/usr/local/lib/python2.7/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/usr/local/lib/python2.7/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/usr/local/lib/python2.7/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/broccoli/161220049_web_programming/blog/app/templates/base.html", line 49, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/broccoli/161220049_web_programming/blog/app/templates/_post.html", line 11, in block "app_content"
    {% for comment in comments %}
TypeError: 'Pagination' object is not iterable
